/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinWorkspaceRouteImport } from './routes/join-workspace'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated.workspace'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated.team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedDiscussionsRouteImport } from './routes/_authenticated.discussions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated.ai'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated.ai.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedDiscussionsDiscussionIdRouteImport } from './routes/_authenticated.discussions.$discussionId'
import { Route as AuthenticatedAiTasksRouteImport } from './routes/_authenticated.ai.tasks'
import { Route as AuthenticatedAiSprintRouteImport } from './routes/_authenticated.ai.sprint'
import { Route as AuthenticatedAiReviewRouteImport } from './routes/_authenticated.ai.review'
import { Route as AuthenticatedAiReleaseNotesRouteImport } from './routes/_authenticated.ai.release-notes'
import { Route as AuthenticatedAiReadmeRouteImport } from './routes/_authenticated.ai.readme'
import { Route as AuthenticatedAiPromptsRouteImport } from './routes/_authenticated.ai.prompts'
import { Route as AuthenticatedAiMeetingRouteImport } from './routes/_authenticated.ai.meeting'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated.ai.insights'
import { Route as AuthenticatedAiHistoryRouteImport } from './routes/_authenticated.ai.history'
import { Route as AuthenticatedAiDocsRouteImport } from './routes/_authenticated.ai.docs'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated.ai.chat'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinWorkspaceRoute = JoinWorkspaceRouteImport.update({
  id: '/join-workspace',
  path: '/join-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscussionsRoute =
  AuthenticatedDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedDiscussionsDiscussionIdRoute =
  AuthenticatedDiscussionsDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => AuthenticatedDiscussionsRoute,
  } as any)
const AuthenticatedAiTasksRoute = AuthenticatedAiTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiSprintRoute = AuthenticatedAiSprintRouteImport.update({
  id: '/sprint',
  path: '/sprint',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiReviewRoute = AuthenticatedAiReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiReleaseNotesRoute =
  AuthenticatedAiReleaseNotesRouteImport.update({
    id: '/release-notes',
    path: '/release-notes',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiReadmeRoute = AuthenticatedAiReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiPromptsRoute = AuthenticatedAiPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiMeetingRoute = AuthenticatedAiMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiHistoryRoute = AuthenticatedAiHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiDocsRoute = AuthenticatedAiDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai': typeof AuthenticatedAiRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discussions': typeof AuthenticatedDiscussionsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/ai/chat': typeof AuthenticatedAiChatRoute
  '/ai/docs': typeof AuthenticatedAiDocsRoute
  '/ai/history': typeof AuthenticatedAiHistoryRoute
  '/ai/insights': typeof AuthenticatedAiInsightsRoute
  '/ai/meeting': typeof AuthenticatedAiMeetingRoute
  '/ai/prompts': typeof AuthenticatedAiPromptsRoute
  '/ai/readme': typeof AuthenticatedAiReadmeRoute
  '/ai/release-notes': typeof AuthenticatedAiReleaseNotesRoute
  '/ai/review': typeof AuthenticatedAiReviewRoute
  '/ai/sprint': typeof AuthenticatedAiSprintRoute
  '/ai/tasks': typeof AuthenticatedAiTasksRoute
  '/discussions/$discussionId': typeof AuthenticatedDiscussionsDiscussionIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discussions': typeof AuthenticatedDiscussionsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/ai/chat': typeof AuthenticatedAiChatRoute
  '/ai/docs': typeof AuthenticatedAiDocsRoute
  '/ai/history': typeof AuthenticatedAiHistoryRoute
  '/ai/insights': typeof AuthenticatedAiInsightsRoute
  '/ai/meeting': typeof AuthenticatedAiMeetingRoute
  '/ai/prompts': typeof AuthenticatedAiPromptsRoute
  '/ai/readme': typeof AuthenticatedAiReadmeRoute
  '/ai/release-notes': typeof AuthenticatedAiReleaseNotesRoute
  '/ai/review': typeof AuthenticatedAiReviewRoute
  '/ai/sprint': typeof AuthenticatedAiSprintRoute
  '/ai/tasks': typeof AuthenticatedAiTasksRoute
  '/discussions/$discussionId': typeof AuthenticatedDiscussionsDiscussionIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/ai': typeof AuthenticatedAiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join-workspace': typeof JoinWorkspaceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai': typeof AuthenticatedAiRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discussions': typeof AuthenticatedDiscussionsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/ai/chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/ai/docs': typeof AuthenticatedAiDocsRoute
  '/_authenticated/ai/history': typeof AuthenticatedAiHistoryRoute
  '/_authenticated/ai/insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/ai/meeting': typeof AuthenticatedAiMeetingRoute
  '/_authenticated/ai/prompts': typeof AuthenticatedAiPromptsRoute
  '/_authenticated/ai/readme': typeof AuthenticatedAiReadmeRoute
  '/_authenticated/ai/release-notes': typeof AuthenticatedAiReleaseNotesRoute
  '/_authenticated/ai/review': typeof AuthenticatedAiReviewRoute
  '/_authenticated/ai/sprint': typeof AuthenticatedAiSprintRoute
  '/_authenticated/ai/tasks': typeof AuthenticatedAiTasksRoute
  '/_authenticated/discussions/$discussionId': typeof AuthenticatedDiscussionsDiscussionIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/activity'
    | '/ai'
    | '/dashboard'
    | '/discussions'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/ai/chat'
    | '/ai/docs'
    | '/ai/history'
    | '/ai/insights'
    | '/ai/meeting'
    | '/ai/prompts'
    | '/ai/readme'
    | '/ai/release-notes'
    | '/ai/review'
    | '/ai/sprint'
    | '/ai/tasks'
    | '/discussions/$discussionId'
    | '/projects/$projectId'
    | '/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/activity'
    | '/dashboard'
    | '/discussions'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/ai/chat'
    | '/ai/docs'
    | '/ai/history'
    | '/ai/insights'
    | '/ai/meeting'
    | '/ai/prompts'
    | '/ai/readme'
    | '/ai/release-notes'
    | '/ai/review'
    | '/ai/sprint'
    | '/ai/tasks'
    | '/discussions/$discussionId'
    | '/projects/$projectId'
    | '/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/join-workspace'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/welcome'
    | '/_authenticated/activity'
    | '/_authenticated/ai'
    | '/_authenticated/dashboard'
    | '/_authenticated/discussions'
    | '/_authenticated/notifications'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/workspace'
    | '/_authenticated/ai/chat'
    | '/_authenticated/ai/docs'
    | '/_authenticated/ai/history'
    | '/_authenticated/ai/insights'
    | '/_authenticated/ai/meeting'
    | '/_authenticated/ai/prompts'
    | '/_authenticated/ai/readme'
    | '/_authenticated/ai/release-notes'
    | '/_authenticated/ai/review'
    | '/_authenticated/ai/sprint'
    | '/_authenticated/ai/tasks'
    | '/_authenticated/discussions/$discussionId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinWorkspaceRoute: typeof JoinWorkspaceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-workspace': {
      id: '/join-workspace'
      path: '/join-workspace'
      fullPath: '/join-workspace'
      preLoaderRoute: typeof JoinWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discussions': {
      id: '/_authenticated/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AuthenticatedDiscussionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/discussions/$discussionId': {
      id: '/_authenticated/discussions/$discussionId'
      path: '/$discussionId'
      fullPath: '/discussions/$discussionId'
      preLoaderRoute: typeof AuthenticatedDiscussionsDiscussionIdRouteImport
      parentRoute: typeof AuthenticatedDiscussionsRoute
    }
    '/_authenticated/ai/tasks': {
      id: '/_authenticated/ai/tasks'
      path: '/tasks'
      fullPath: '/ai/tasks'
      preLoaderRoute: typeof AuthenticatedAiTasksRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/sprint': {
      id: '/_authenticated/ai/sprint'
      path: '/sprint'
      fullPath: '/ai/sprint'
      preLoaderRoute: typeof AuthenticatedAiSprintRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/review': {
      id: '/_authenticated/ai/review'
      path: '/review'
      fullPath: '/ai/review'
      preLoaderRoute: typeof AuthenticatedAiReviewRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/release-notes': {
      id: '/_authenticated/ai/release-notes'
      path: '/release-notes'
      fullPath: '/ai/release-notes'
      preLoaderRoute: typeof AuthenticatedAiReleaseNotesRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/readme': {
      id: '/_authenticated/ai/readme'
      path: '/readme'
      fullPath: '/ai/readme'
      preLoaderRoute: typeof AuthenticatedAiReadmeRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/prompts': {
      id: '/_authenticated/ai/prompts'
      path: '/prompts'
      fullPath: '/ai/prompts'
      preLoaderRoute: typeof AuthenticatedAiPromptsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/meeting': {
      id: '/_authenticated/ai/meeting'
      path: '/meeting'
      fullPath: '/ai/meeting'
      preLoaderRoute: typeof AuthenticatedAiMeetingRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/insights': {
      id: '/_authenticated/ai/insights'
      path: '/insights'
      fullPath: '/ai/insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/history': {
      id: '/_authenticated/ai/history'
      path: '/history'
      fullPath: '/ai/history'
      preLoaderRoute: typeof AuthenticatedAiHistoryRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/docs': {
      id: '/_authenticated/ai/docs'
      path: '/docs'
      fullPath: '/ai/docs'
      preLoaderRoute: typeof AuthenticatedAiDocsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/chat': {
      id: '/_authenticated/ai/chat'
      path: '/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
  }
}

interface AuthenticatedAiRouteChildren {
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedAiDocsRoute: typeof AuthenticatedAiDocsRoute
  AuthenticatedAiHistoryRoute: typeof AuthenticatedAiHistoryRoute
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedAiMeetingRoute: typeof AuthenticatedAiMeetingRoute
  AuthenticatedAiPromptsRoute: typeof AuthenticatedAiPromptsRoute
  AuthenticatedAiReadmeRoute: typeof AuthenticatedAiReadmeRoute
  AuthenticatedAiReleaseNotesRoute: typeof AuthenticatedAiReleaseNotesRoute
  AuthenticatedAiReviewRoute: typeof AuthenticatedAiReviewRoute
  AuthenticatedAiSprintRoute: typeof AuthenticatedAiSprintRoute
  AuthenticatedAiTasksRoute: typeof AuthenticatedAiTasksRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
}

const AuthenticatedAiRouteChildren: AuthenticatedAiRouteChildren = {
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedAiDocsRoute: AuthenticatedAiDocsRoute,
  AuthenticatedAiHistoryRoute: AuthenticatedAiHistoryRoute,
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedAiMeetingRoute: AuthenticatedAiMeetingRoute,
  AuthenticatedAiPromptsRoute: AuthenticatedAiPromptsRoute,
  AuthenticatedAiReadmeRoute: AuthenticatedAiReadmeRoute,
  AuthenticatedAiReleaseNotesRoute: AuthenticatedAiReleaseNotesRoute,
  AuthenticatedAiReviewRoute: AuthenticatedAiReviewRoute,
  AuthenticatedAiSprintRoute: AuthenticatedAiSprintRoute,
  AuthenticatedAiTasksRoute: AuthenticatedAiTasksRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
}

const AuthenticatedAiRouteWithChildren = AuthenticatedAiRoute._addFileChildren(
  AuthenticatedAiRouteChildren,
)

interface AuthenticatedDiscussionsRouteChildren {
  AuthenticatedDiscussionsDiscussionIdRoute: typeof AuthenticatedDiscussionsDiscussionIdRoute
}

const AuthenticatedDiscussionsRouteChildren: AuthenticatedDiscussionsRouteChildren =
  {
    AuthenticatedDiscussionsDiscussionIdRoute:
      AuthenticatedDiscussionsDiscussionIdRoute,
  }

const AuthenticatedDiscussionsRouteWithChildren =
  AuthenticatedDiscussionsRoute._addFileChildren(
    AuthenticatedDiscussionsRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscussionsRoute: typeof AuthenticatedDiscussionsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiRoute: AuthenticatedAiRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscussionsRoute: AuthenticatedDiscussionsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinWorkspaceRoute: JoinWorkspaceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
